### PR TITLE
Health check: trusted users

### PR DESCRIPTION
**Pull request by shivaraj-bh**

### CODE REVIEW

**Comment by srid** [comment]
https://github.com/juspay/nix-browser/pull/42/commits/5dbb42bccb5c4327d7ea9d3c9921f3c0c672149a might be relevant

**Comment by srid** [comment]
Heads up: I'm going to merge #53 soon which will introduce further conflicts. Sorry about that. 

(Trying to prevent a monolith unmaintainable crate)

**Comment by srid** [comment]
@shivaraj-bh #53 is now merged. It may be simpler to just re-do your changes on top of new `main` than resolve conflicts.

Note that there should be no UI code in `crates/nix*` crates; they represent just rust libraries, which may also get used in other CLI programs (nix-health for example).

**Comment by shivaraj-bh** [comment]
Opening a new PR instead of resolving a bazillion conflicts

**Pull request closed without merging**
