### PR TITLE
`om show` nixosConfigurations

### PR DESCRIPTION
**Pull request by shivaraj-bh**

### CODE REVIEW

**Comment by shivaraj-bh** [comment]
`om show github:srid/nixos-config`:

```sh
🐧 NixOS Configurations

Run: nixos-rebuild switch --flake .#<name>
───────────┬─────────────
 name      │ description
═══════════┼═════════════
 immediacy │ N/A
───────────┴─────────────
```

(You are viewing the tail of the output)

**Review by srid — APPROVED** [review]
LGTM. Could you update the `nix_rs` ChangeLog accordingly?

See https://github.com/juspay/omnix?tab=readme-ov-file#contributing

**Comment by shivaraj-bh** [comment]
> LGTM. Could you update the `nix_rs` ChangeLog accordingly?
> 
> See https://github.com/juspay/omnix?tab=readme-ov-file#contributing

Done

**Review by srid — CHANGES_REQUESTED** [review]
This just occured to me. Could you make the necessary change in `omnix-gui` as well? I don't see `NixOS Configurations' section in the GUI:

image

While we may not care about GUI parity yet (since CLI is the priority), we should at least try to keep it in sync unless the change will be complex.

**Comment by shivaraj-bh** [comment]
image

**Pull request merged**
